# Generated by Django 6.1 on 2026-08-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Код категории (источник)'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Код продукта (источник)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название продукта'),
        ),
    ]
