# Generated by Django 6.1 on 2026-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_slug_product_external_id_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Артикул'),
        ),
    ]
