# Generated by Django 6.1 on 2026-08-28 03:13

from django.db import migrations, models

MEDIA_BASE_URL = 'https://api.protool.kg/media/'


def absolutize_existing_media(apps, schema_editor):
    """Уже скачанные ранее файлы остаются на диске и отдаются Django/nginx
    по /media/ — превращаем их относительные пути в абсолютные ссылки на
    бэкенд, чтобы после смены полей на URLField они продолжали открываться
    так же, как раньше (парсер больше ничего не скачивает — см. commit)."""
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')

    for model, fields in ((Product, ('image', 'product_certificate')), (ProductImage, ('image',))):
        for obj in model.objects.all().iterator():
            changed = False
            for field in fields:
                value = getattr(obj, field)
                if value and not value.startswith(('http://', 'https://')):
                    setattr(obj, field, MEDIA_BASE_URL + value.lstrip('/'))
                    changed = True
            if changed:
                obj.save(update_fields=list(fields))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Изображение продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_certificate',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Сертификат продукта'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='Изображение'),
        ),
        migrations.RunPython(absolutize_existing_media, noop),
    ]
